language: node_js
node_js: 
  - "node"

services:
  - postgresql

cache:
  directories: 
    - "node_modules"
before_install:
  - "npm install"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
 - npm run coverage

 env: 
  - DATABASE_URL=postgres://postgres:yankee123@127.0.0.1:5432/politico_db
script:
  - "npm run test"
 
